spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb
    username: sa
    password:

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

