name: Push Backend DockerHub
on:
  push:
    branches: [ develop ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Spring Application Build
        run: ./gradlew build

      - name: Docker Image Build
        run: docker build -t rxjw95/flavorite-hub .

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_JW_ID }}
          password: ${{ secrets.DOCKERHUB_JW_TOKEN }}

      - name: Docker Hub Publish
        run: docker push rxjw95/flavorite-hub
