name: Frontend Docker Code Deploy
on:
  push:
    branches: [ develop ]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Docker Image Build
        run: docker build -t corat/flavorite-hub .

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_SE_ID }}
          password: ${{ secrets.DOCKERHUB_SE_TOKEN }}

      - name: Docker Hub Publish
        run: docker push corat/flavorite-hub

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            sudo docker stop $(sudo docker ps --filter "name=flavorite-fe" -a -q) 
            sudo docker rm $(sudo docker ps --filter "name=flavorite-fe" -a -q) 
            sudo docker pull corat/flavorite-hub
            sudo docker run -d -p 3000:3000 --name flavorite-fe corat/flavorite-hub
