name: PR Labeler
on:
  pull_request:
    types: [ opened, reopened, edited ]
    branches:
      - feature/se/feature-labeler
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: PR Labeler
        uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml
